### ISSUE TITLE
Bug in Step 2 with background pic set

### ISSUE THREAD

**Issue by abhirupms003** [carbon-design-system/carbon-for-ibm-dotcom-tutorial#158]
Hi, 
I'm new to carbon components and started with carbon design system tutorials.
I am facing an issue in Step 2. of https://www.ibm.com/standards/carbon/developing/web-components-tutorial/step-2/
This issue is the background picture is not reflecting in the webpage.
attaching the INDEX.HTML for check. Please guide as needed, thanks

[index.txt](https://github.com/carbon-design-system/carbon-for-ibm-dotcom-tutorial/files/8927208/index.txt)
image (1)

I  raised a question on the same but later I was able to resolve the issue by re-ordering the imports in app.js , the issue got resolved. It seems to be a bug. please check.
link : 
[https://github.com/carbon-design-system/carbon-for-ibm-dotcom-tutorial/issues/157#issue-1274943362]

**Comment by ariellalgilmore** [comment]
more info here: https://ibm-studios.slack.com/archives/C2PLX8GQ6/p1655466211527669
