### ISSUE TITLE
yarn ci-check fails on windows machines

### ISSUE THREAD

**Issue by ricardo-reis1** [carbon-design-system/carbon-for-ibm-dotcom-tutorial#88]
Describe the issue:
yarn ci-check fails on windows machines.

> What happens?
![image](https://user-images.githubusercontent.com/72280534/162257820-3fc1a5c8-c0a8-4269-91be-9f82483eacbe.png)

> What should happen?
![image](https://user-images.githubusercontent.com/72280534/162257089-543908d7-c509-45fd-9617-917ce6f54fe5.png)

Steps to reproduce the issue:

1.open terminal (on windows)
2.yarn ci-check
3.read the error

Please provide any additional notes:
The issue can be fixed by replacing the "lint:styles" script on the package.json:
`"lint:styles": "stylelint '**/*.{css,scss}'",`
with:
`"lint:styles": "stylelint \"src/**/*.{css,scss}\"",`

*Priority
Low Priority

**Comment by kennylam** [comment]
Resolved in 59b083a.
